const pricingPlan = retrievePricingPlan();
const baseCharge = pricingPlan.baseCharge;
let charge;
const chargePerUnit = princingPlan.unit;
const order = retreiveOrder();
const units = order.units;
charge = baseCharge + units * chargePerUnit;
let discountableUnits = Math.max(units - pricingPlan.discountThreshold, 0);
let discount;
discount = discountableUnits * pricingPlan.discountFactor;
if (order.isRepeat) discount += 20;
charge = charge - discount;
chargeOrder(charge);
